[build]
  command = "prisma generate && prisma db push --accept-data-loss && prisma db seed && npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/client/*.node"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
